### ISSUE TITLE
Please publish latest version to pypi with read_from_end arg

### ISSUE THREAD

**Issue by kgreenek** [bgreenlee/pygtail#43]
Sorry for filing this as an issue, I'm not sure how else to communicate my request.

I'm using pygtail with a large log file. I'd benefit a lot from having the read_from_end arg. However it isn't released in the latest version of pygtail in pypi (v0.8.0). If you have time, could you please publish a v0.9.0 with the latest code? I would really appreciate it!

Pygtail is great btw! Awesome work.

**Comment by bgreenlee** [comment]
Ok, done. Sorry for the delay.
