### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 6832: invalid continuation byte

### ISSUE THREAD

**Issue by royobrecht** [bgreenlee/pygtail#48]
Because I can't control the source log file, there needs to be a way to either ignore or handle these error exceptions. Unless you are the one who wrote the application that is writing to the log file and thus have full control over it, this issue is going to continue to come up.  I tried to pre-process the log file in ftfy first but that did not solve this problem.

Traceback (most recent call last):
  File "./ConsoleMon_0.3.py", line 27, in <module>
    for line in Pygtail(ftfy.fix_text("/home/hserver/prod/server4/log/console/hserver-console.log")):
  File "/home/hserver/.local/lib/python3.6/site-packages/pygtail/core.py", line 134, in __next__
    return self.next()
  File "/home/hserver/.local/lib/python3.6/site-packages/pygtail/core.py", line 106, in next
    line = self._get_next_line()
  File "/home/hserver/.local/lib/python3.6/site-packages/pygtail/core.py", line 277, in _get_next_line
    line = self._filehandle().readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 6832: invalid continuation byte

**Comment by royobrecht** [comment]
This is the same error with the version of my script that does not use ftfy.  The problem is not seen if I rotate out the log file which happens automatically once a day.  My monitoring script fails once or twice per day.  There are many international users making comments with all sorts of special characters. It might make a good corner case test log.  I could make the log file available to you privately.  

Traceback (most recent call last):
  File "./ConsoleMon_0.2.py", line 26, in <module>
    for line in Pygtail("/home/hserver/prod/server4/log/console/hserver-console.log"):
  File "/home/hserver/.local/lib/python3.6/site-packages/pygtail/core.py", line 134, in __next__
    return self.next()
  File "/home/hserver/.local/lib/python3.6/site-packages/pygtail/core.py", line 106, in next
    line = self._get_next_line()
  File "/home/hserver/.local/lib/python3.6/site-packages/pygtail/core.py", line 277, in _get_next_line
    line = self._filehandle().readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 6832: invalid continuation byte

**Comment by magneticstain** [comment]
I've encountered this bug in my project as well as it utilizes pygtails for log file parsing. I've included what I believe is the root cause of this, as well as a possible fix, in the issue details.

https://github.com/magneticstain/Inquisition/issues/7

**Comment by royobrecht** [comment]
Thanks @Magneticstain,

Failing gracefully as you recommended would be great since by the very nature of what many would use pygtail for is to monitor logs written by applications that you cannot control what is being written to them.  I would not like to simply ignore the line, but the option do something with it. My goal is to write the offending line to an error log file with the referenced line number of the original log. I can then do analysis if I chose to.

**Comment by mlin** [comment]
It's possible to hit essentially the same problem even when the target program generates valid utf-8 logs; if, at the instant Pygtail reads the log file, a multibyte utf-8 character has been only partially written out.

This actually happened to me, believe it or not, with the following message from /bin/mv:

```
mv: cannot remove ‘/mnt/miniwdl_task_container/inputs/0/sorted.bam’: Device or resource busy
```

Which uses the ["Right Single Quotation Mark"](https://www.fileformat.info/info/unicode/char/2019/index.htm], U+2019, 0xE2 0x80 0x99.

repro:

```
$ rm -f mylog.offset
$ echo -ne "mv: cannot remove \xE2\x80\x99" > mylog
$ python3 -c 'import pygtail; [print(line) for line in pygtail.Pygtail("mylog")]'
mv: cannot remove ’
$ echo -ne "mv: cannot remove \xE2" >> mylog
$ python3 -c 'import pygtail; [print(line) for line in pygtail.Pygtail("mylog")]'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
  File "/home/mlin/src/pygtail/pygtail/core.py", line 136, in __next__
    return self.next()
  File "/home/mlin/src/pygtail/pygtail/core.py", line 108, in next
    line = self._get_next_line()
  File "/home/mlin/src/pygtail/pygtail/core.py", line 280, in _get_next_line
    line = self._filehandle().readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 0: unexpected end of data
```

cc @MDunitz

**Comment by beyondmeat** [comment]
I've tried multiple tail modules out there and all of them have this issue.

Anyway to workaround it?

**Comment by kristianronningen** [comment]
I'm getting this error on a semi-regular basis on some mailserver logs, and I can't seem to figure out what character(s) are causing the issue. Since I only use it to gather some statistics, skipping an unreadable line is not an issue for me. I tried the suggested fix from https://github.com/bgreenlee/pygtail/issues/48#issuecomment-487313953 but that gave me another error (`AttributeError: 'Pygtail' object has no attribute 'read_from_end'`). I've only managed to get rid of this error by removing the offset file and start fresh, but this is not really an ideal solution.

**Comment by royobrecht** [comment]
After a long while, I took another look at the problem.  It's with the codecs.py file within python libraries.  I made the following change, adding try:/except:, to debug it and my crashes went away.  Need to do something better since I'm just ignoring the problem,  but it's working normally for most of the time.  This is non critical data so, I'm not too worried about missing a few lines.  Crashing is worse!  I will probably file a bug report for codecs.py.  It shouldn't be just crashing when it can't handle the data.

/usr/lib/python3.6# diff -H  codecs.py codecs.orig.py
321,327c321
<         #adding Try/Except to debug a codec crash situation
<         try:
<             (result, consumed) = self._buffer_decode(data, self.errors, final)
<         except:
<             #debug setting result, consumed to " " for situation where the try line errors out.
<             (result, consumed) = (" ", " ", final)
<
---
>         (result, consumed) = self._buffer_decode(data, self.errors, final)

**Comment by razvanpaul-mielcioiu** [comment]
If someone wants to use a hack, I solved my issue by changing this in `/site-packages/pygtail/core.py`:
`self._fh = open(filename, "r", 1)`
into this:
`self._fh = open(filename, "r", 1, encoding='latin-1')`

reference: https://stackoverflow.com/questions/30996289/utf8-codec-cant-decode-byte-0xf3

**Comment by Spud1001** [comment]
Is this issue now closed thanks to PR https://github.com/bgreenlee/pygtail/pull/33? @bgreenlee
