### ISSUE TITLE
Error when launch pygtail from command line 

### ISSUE THREAD

**Issue by saibug** [bgreenlee/pygtail#60]
hi team 
i have installed pygtail from sources, and after when i launch it from cmdline, i get this error !! 
`The 'pygtail==0.11.1' distribution was not found and is required by the application`

also , i'm unable to import module from my venv :/ 
```
>>> from pygtail import Pygtail
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pygtail'
```
pip3.6 
python3.6 
os : RHEL7.6 

Any suggestions ?

**Comment by bgreenlee** [comment]
Sorry, I'm not sure what would cause that. Is there a reason you're installing from sources rather than via `pip install`?

**Comment by saibug** [comment]
Solved
I have just uninstall/install packages with pip3.6 

Thanks
